### ISSUE TITLE
click/tap outside?

### ISSUE THREAD

**Issue by oyeanuj** [davidtheclark/teeny-tap#2]
Hi @davidtheclark! Here via your comment on react-click-outside today. 

I noticed that this library only creates a consistent listener for clicks and taps. Just wondering if you have an example or code snippet that shows how to use this library to determine if the tap is outside the element, similar to the usecase in react-click-outside?

Thanks, as always, for putting your work out there! :)

**Comment by davidtheclark** [comment]
react-aria-menubutton does this, e.g. https://github.com/davidtheclark/react-aria-menubutton/blob/345765e5cae69cd5f001967fd257eec20e2f09fc/lib/Menu.js#L60
